name: Build and Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-18 clang-tidy-18
          sudo ln -sf /usr/bin/clang-format-18 /usr/bin/clang-format
          sudo ln -sf /usr/bin/clang-tidy-18 /usr/bin/clang-tidy
          sudo ln -sf /usr/bin/run-clang-tidy-18 /usr/bin/run-clang-tidy
      
      - name: Check format
        run: |
          find . -path ./build -prune -o -path ./graph/build -prune -o -type f -name '*.[c|h]' -print | xargs clang-format --style=file --dry-run -Werror
      
      - name: Build and Test Main Task
        run: |
          cmake . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          cmake --build build
          run-clang-tidy -p=build
          if [ -f run_tests.sh ]; then
            chmod +x run_tests.sh
            ./run_tests.sh
          fi

      - name: Build and Test Graph Task
        run: |
          if [ -d "graph" ]; then
            cd graph
            cmake . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            cmake --build build
            run-clang-tidy -p=build
            if [ -f run_tests.sh ]; then
              chmod +x run_tests.sh
              ./run_tests.sh
            fi
          fi
