name: Build and Lint

on:
  push:
    branches: [ main, master, avl_tree ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy clang-format cmake

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: clang-tidy
        run: |
          run-clang-tidy -p build -checks='-*,bugprone-*,cert-*,clang-analyzer-*,cppcoreguidelines-*,misc-*,modernize-*,performance-*,readability-*,-clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling'

      - name: clang-format
        run: |
          find . -path ./build -prune -o -name '*.[c|h]' -print | xargs clang-format --dry-run --style=WebKit --Werror

      - name: Build
        run: |
          cmake --build build
