name: C Project CI

on: [push, pull_request]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format clang-tidy cmake
      
    - name: Check Formatting
      run: |
        find . -path ./build -prune -o -name '*.[ch]' -print | xargs clang-format --style=WebKit --dry-run --Werror

    - name: Static Analysis
      run: |
        FILES=$(find . -name "*.c" -not -path "./build/*")
        if [ -z "$FILES" ]; then
          echo "Файлы .c не найдены, пропускаю анализ."
        else
          echo "$FILES" | xargs clang-tidy --checks='-*,bugprone-*,cert-*,clang-analyzer-*,readability-*' -- -IDFA/src -Isrc
        fi
    - name: Build and Test
      run: |
        cmake -S . -B build
        cmake --build build
        find build -name "test*" -type f -executable -exec {} +
